#%RAML 1.0 Trait
  usage: To identity transaction with transaction id
  headers:
      x-transaction-id:
        description: Transaction id
        type: string
        required: false
        example: "16e17d0c-33d4-4620-99b6-d66784b9975a"